README.md
Always struggle trying to remember how to set up and run the bot for local testing after I haven't touched it for a while. Please feel free to chime in if there is any better way to do what I described in the quick start section.
=> Update readme to include all required dependencies and add quick setup section

season_configs/winter_2019.yaml
Here are the links for your convenience: 
https://www.hulu.com/series/the-promised-neverland-3ef087c6-d967-4495-9730-b5ff54ded8e0
https://www.hulu.com/series/kaguya-sama-love-is-war-da69fc06-cdea-42dc-8827-52cee194db54
=> Added Hulu links for Promised Neverland and Kaguya

src/services/__init__.py
@bainosz - Fixes #32
Reasons I made this a PR instead of just committing it myself:
- Does 10 seconds work as the timeout time? The requests documentation says that's the maximum time between data packets being sent, not max download time, so it should be more than enough, but you'd know better than me
- I don't have the means to test this, so probably do that before merging :P
=> Add timeouts to network requests

season_configs/spring_2019.yaml
Added Crunchyroll urls for Kenja no Mago, YU-NO, and Nande koko ni sensei ga!? for the spring_2019.yaml config file.
=> Update spring_2019.yaml with some Crunchyroll urls

README.md, config.ini, src/module_find_episodes.py, src/reddit.py
New episodes are now added to the list of episodes in previous discussions
Test subreddit: https://www.reddit.com/r/dmiumholotest/
Fixes #35
=> Retroactively add future episodes

season_configs/summer_2020.yaml
monster musume no Oisha-san, absolutely nothing to do with Monster Musume from before, hopefully it's a fun show
=> add monster girl doctor

season_configs/summer_2020.yaml
Added some urls for Deca-Dence, hope this is the right repo!
=> Added stream urls for Deca-Dence, summer_2020.yaml

season_configs/fall_2020.yaml
from #sub-bots-dev, https://discord.com/channels/267799767843602452/731581603322658906/791879714414919690 and https://mod.reddit.com/mail/new/jcncy
=> Add funimation stream for AoT S4

season_configs/spring_2021.yaml
Added a few subreddits that were originally added elsewhere but got missed.
=> Some missed subreddits for Spring 21

season_configs/summer_2021.yaml
=> Revert "Update summer_2021.yaml"

season_configs/fall_2021.yaml
=> Fixed Demon Slayer Entertainment Arc info

season_configs/winter_2022.yaml
- Adds subreddits
- Fixes up titles to "Season X" format. (Arifureta + Takagi-San)
- Removes "Kimetsu no Yaiba Entertainment District Arc" as this is already being managed from last season
=> Winter2022 subreddits and title fixes

season_configs/winter_2022.yaml
Minor addition. Did not find any other differences from Anilist
=> Attack on Titan VRV stream

season_configs/winter_2022.yaml
Adds Shenmue the Animation, streams for precure and others.
=> Adds Shenmue the Animation, streams for precure and others.

season_configs/winter_2022.yaml
Fixed the subreddit link for Akebi-chan no Sailor-fuku so it points to the right one.
=> Fix subreddit link for Akebi-chan no Sailor-fuku

season_configs/spring_2022.yaml
Add some missing subreddits and mal/anilist links
=> Adding missing links for spring 2022

season_configs/winter_2023.yaml
Expanding Badspler's work in #147 to add subreddits.
I've added some comments on some of the subreddits I've found - such as low traffic or having zero (or minimal) CSS. 
If someone could let me know what minimal requirments I should look for when finding subreddits, it would be appreciated.
=> Expand #147 with subreddits

src/reddit.py
Found while attempting to make a batch release.
=> Use proper key for getting flair ids

season_configs/spring_2023.yaml
Expands the work done by Badspler and adds a bunch of subreddits
=> Expand work by Badspler

season_configs/spring_2023.yaml
- Early draft for an initial look.
=> Spring 2023

season_configs/spring_2023.yaml
- More streams
- Subreddit fixes
- Source fixes
- EN Title fixes
=> Additional streams, fixes and such Spring 2023

season_configs/spring_2023.yaml
Additional Streams for Spring 2023
=> Adds additional streams

season_configs/summer_2023.yaml
Initial load
- https://www.livechart.me/summer-2023/tv
=> 2023 summer initial load

season_configs/summer_2023.yaml
Additional Streams - Summer 2023
=> Additional streams - Summer 2023

season_configs/fall_2023.yaml
adds apothecary diaries stream to finalize fall 23
=> adds apothecary diaries stream

season_configs/winter_2024.yaml
Fixes the YAML linting from this run https://github.com/r-anime/holo/actions/runs/8447202965/job/23137153433
=> Fix yaml linting in winter_2024.yaml

season_configs/spring_2024.yaml
=> Draft of Spring 2024

season_configs/spring_2024.yaml
=> Additional spring2024 streams

season_configs/spring_2024.yaml, season_configs/winter_2024.yaml
Final season wrap up Spring 2024
=> Final season wrap up Spring 2024

season_configs/summer_2024.yaml
- Adds additional seasonal streams - summer2024
=> Adds additional seasonal streams - summer2024

season_configs/summer_2024.yaml
- Adds additional streams subs and fixes
=> Summer 2024 - Additional Streams

season_configs/fall_2024.yaml
Added Netflix links to Ranma 1/2, Dan Da Dan, Orb.
=> Added some Fall 2024 Netflix links

season_configs/winter_2025.yaml
=> Winter 2025

season_configs/winter_2025.yaml
Adds URLs for a few more Crunchyroll streams in the Winter 2025 season configs.
Hope I'm doing this right. Had some SQLite issues and didn't quite get the development environment working, so I just manually edited these in.
=> More winter 2025 CR streams

season_configs/winter_2025.yaml
=> Additional streams 

season_configs/spring_2025.yaml
=> WIP Spring 2025 YAML

season_configs/spring_2025.yaml
=> Additional Streams

season_configs/summer_2025.yaml
=> WIP: 2025 summer

src/module_batch_create.py, src/module_find_episodes.py, src/reddit.py
and also rename the method, since they're not short links anymore.
Note this is not tested at all. I didn't even setup the python interpreter cause I hate setting up python projects and last time it took me 2 hours. It's a simple change, so there shouldn't be any issues with it.
=> use configured subreddit in the long links 
